# Generated by Django 3.2.4 on 2023-12-13 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('lesson', '0002_attendance_studentscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(to='account.Group'),
        ),
        migrations.AlterField(
            model_name='studentscores',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
